kubectl apply -f - <<EOF
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.wait.play.com
spec:
  group: wait.play.com
  scope: Namespaced
  names:
    kind: MySQL
    listKind: MySQLList
    singular: mysql
    plural: mysqls
    shortNames:
      - mysql
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
                bar:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Foo
          type: string
          description: Status of the Foo
          jsonPath: .spec.foo
        - name: Bar
          type: string
          description: Status of the Bar
          jsonPath: .spec.bar
EOF
  
kubectl apply -f - <<EOF
apiVersion: "wait.play.com/v1"
kind: MySQL
metadata:
  name: mysql
spec:
  foo: my-awesome-foo
  bar: my-awesome-bar
EOF