
spring.thymeleaf.cache: false
server.servlet.context-path: /


server.port: 9443
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: 111111
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat
