apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummys.wait.play.com
spec:
  group: wait.play.com
  scope: Namespaced
  names:
    kind: Dummy
    listKind: DummyList
    singular: dummy
    plural: dummys
    shortNames:
      - dm
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
                bar:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Foo
          type: string
          description: Status of the Foo
          jsonPath: .spec.foo
        - name: Bar
          type: string
          description: Status of the Bar
          jsonPath: .spec.bar
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
          description: Create datetime