apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hello-template
spec:
  params:
    - name: username
      default: "Tekton"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hello-run-
      spec:
        pipelineRef:
          name: hello
        params:
          - name: username
            value: $(tt.params.username)