apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: hello-trigger
      bindings:
        - ref: hello-binding
      template:
        ref: hello-template
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('content-Type', 'application/json')"
            - name: "overlays"
              value:
                - key: username
                  expression: "body.username.upperAscii()"