apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-binding
spec:
  params:
    - name: username
      # $(extensions.username) come from the cel interceptor overlays
      value: "$(extensions.username) -- $(body.username)"