apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: username
      type: string
  steps:
    - name: say-hello
      image: alpine:3.18.3
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/sh
        echo "Hello $(params.username)"