apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
spec:
  description: Read and display README file.
  workspaces:
    - name: source
  steps:
    - name: read
      image: alpine:3.18.3
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/sh
        pwd
        cat $(workspaces.source.path)/README.md